# Generated by Django 5.1.3 on 2024-11-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_logging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthlog',
            name='age',
            field=models.IntegerField(),
        ),
    ]
